#!/bin/sh

project_dir=/home/joscha/gocode/src/bitbucket.org/joscha/hpfeed
command_dir=/home/joscha/opt/hpfeed
goroot=/home/joscha/opt/go

GOPATH=${project_dir}
GOROOT=${goroot}
PATH=$PATH:${goroot}/bin
export GOPATH GOROOT PATH

echo "--> changing to project directory ..."
cd ${project_dir}

echo "--> checkout source ..."
GIT_WORK_TREE=${project_dir} git checkout -f master

echo "--> installing dependencies ..."
go get

echo "--> compiling ..."
go build

echo "--> changing file permission ..."
chmod 700 ${project_dir}/hpeed

# echo "--> stopping hpfeed ..."
# svc -d /home/joscha/service/hpfeed"

# echo "--> delete old version ..."
# rm ${command_dir}/hpfeed

# echo "--> coping to destination ..."
# mv hpfeed ${command_dir}

# echo "--> Starting ..."
# svc -u /home/joscha/service/${binary_name}"
