#!/bin/sh

project_dir=/home/joscha/gocode/src/bitbucket.org/joscha/hpfeed
command_dir=/home/joscha/opt/hpfeed
goroot=/home/joscha/opt/go
gopath=/home/joscha/gocode

GIT_DIR=.git
GOPATH=${gopath}
GOROOT=${goroot}
PATH=$PATH:${goroot}/bin
GIT_WORK_TREE=${project_dir}
export GOPATH GOROOT PATH GIT_DIR GIT_WORK_TREE

echo git_work_tree: $GIT_WORK_TREE
echo git_dir: $GIT_DIR
echo path: $PATH
echo gopath: $GOPATH
echo goroot: $GOROOT

echo "--> changing to project directory ..."
cd ${project_dir}

echo "--> checkout source ..."
git checkout -f master

echo "--> installing dependencies ..."
go get

echo "--> compiling ..."
go build

echo "--> changing file permission ..."
chmod 700 ${project_dir}/hpfeed

# echo "--> stopping hpfeed ..."
svc -d /home/joscha/service/hpfeed"

# echo "--> delete old version ..."
rm ${command_dir}/hpfeed

# echo "--> coping to destination ..."
mv hpfeed ${command_dir}

# echo "--> Starting ..."
svc -u /home/joscha/service/${binary_name}"
